language: java
script: mvn -Psafer -Pintegration -Passembler -B -e -T 1C verify
jdk:
- oraclejdk8
- oraclejdk7

before_script:
- export GIT_BRANCH=$TRAVIS_BRANCH

sudo: false

before_deploy:
  - echo "<settings><servers><server><id>ossrh-snapshot</id><username>\${env.MAVEN_DEPLOY_USER}</username><password>\${env.MAVEN_DEPLOY_PASS}</password></server><server><id>ossrh-release</id><username>\${env.MAVEN_DEPLOY_USER}</username><password>\${env.MAVEN_DEPLOY_PASS}</password></server></servers></settings>" > ~/settings.xml

deploy:
- provider: script
  script: mvn -B -e -T 1C -Pdeploy -DskipTests=true deploy --settings ~/settings.xml
  skip_cleanup: true
  on:
    repo: 8kdata/mongowp
    branch: devel
    jdk: oraclejdk8
  
